### ISSUE TITLE
There is a big issue here.

### ISSUE THREAD

**Issue by abdulbasit-94** [robit-dev/tailwindcss-class-combiner#2]
import mergeClasses from "@robit-dev/tailwindcss-class-combiner";
mergeClasses('text-sm text-bold', 'text-red' , 'text-semibold text-lg', 'text-blue');

This is not going to work fine. only one text- will work when we run this and this will also not override classes.

**Comment by jayge-ekenstam** [comment]
Unfortunately this was a bit beyond our use case, and would make this package quite a bit more complex. As an alternative you may want to look at using [tailshake](https://www.npmjs.com/package/tailshake).
